trigger:
- main

pool:
  name: pipelinehq  # agente auto-hospedado com Docker instalado

variables:
  acrName: registrycyclopay-abfzejg7fudecmhz.azurecr.io
  imageName: $(acrName)/meuapp:testandoapipe

steps:
- script: |
    echo "Criando Dockerfile..."
    cat <<EOF > Dockerfile
    FROM alpine:latest
    RUN echo 'teste OK' > /etc/testandoapipe.txt
    CMD ["cat", "/etc/testandoapipe.txt"]
    EOF
  displayName: Criar Dockerfile

- script: |
    docker build -t $(imageName) .
  displayName: Build da imagem Docker

- task: Docker@2
  displayName: Push para o ACR
  inputs:
    containerRegistry: 'registrycyclopay'  # Nome da Service Connection
    repository: 'meuapp'
    command: 'push'
    tags: 'testandoapipe'
